name: "Update Docker Hub Description"

on:
  push:
    branches: main
    paths:
      - README.md
      - .github/workflows/docker-description.yml
jobs:
  dockerHubDescription:
    name: "Docker Hub update description"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: 3lr1ck/excalibur
